server:
  port: 8080
spring:
  application:
    name: sales

# Keycloak configuration
keycloak:
  auth-server-url: http://localhost:8080
  realm: my_realm
  resource: my_client
  credentials:
    secret: HKFKYP7kb8OMldAgfvnk27FhRPOv8Y7H

---
spring:
  profiles: default
  jpa:
    generate-ddl: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: sales
          destination: newtest
          contentType: application/json
        event-out:
          destination: newtest
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8083

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: sales
          destination: newtest
          contentType: application/json
        event-out:
          destination: newtest
          contentType: application/json


